name: Test
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install npm dependencies
              run: npm ci

            - name: Run lint
              run: npm run eslint

            - name: Run tsc
              run: npm run tsc:check
